---
# http://taigaio.github.io/taiga-doc/dist/setup-production.html

- name: Update apt
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - build-essential
    - binutils-doc
    - autoconf
    - flex
    - bison
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libzmq3-dev
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - libtool
    - libffi-dev
    - curl
    - git
    - tmux
    - gettext

- name: Setup a database
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - postgresql-9.3
    - postgresql-contrib-9.3
    - postgresql-doc-9.3
    - postgresql-server-dev-9.3
    - postgres-xc
  register: init_db

- name: setup initial user and DB
  when: init_db.changed
  shell:
    cmd: "{{item}}"
  with_items:
    - sudo -u postgres createuser taiga
    - sudo -u postgres createdb taiga -O taiga

- name: Setup python environment
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python3
    - python3-pip
    - python-dev
    - python3-dev
    - python-pip
    - virtualenvwrapper
    - libxml2-dev
    - libxslt-dev

- name: Create system user for software
  user:
    name: taiga
    group: taiga
    state: present

- name: Download the code from github
  git:
    repo: https://github.com/taigaio/taiga-back.git
    version: stable
    dest: /home/taiga/taiga-back

- name: Create virtualenv and install requirements
  command: virtualenv /home/taiga/taiga-back/venv -p python3.4

- name: Create virtualenv and install requirements
  pip:
    virtualenv: /home/taiga/taiga-back/venv
    requirements: /home/taiga/taiga-back/requirements.txt

- name: Change owner of github cloned project
  file:
    path: /home/taiga/taiga-back
    state: directory
    recurse: yes
    owner: taiga
    group: taiga

- name: Copy install script
  copy:
    src: install.sh
    dest: /home/taiga/taiga-back/install.sh
    owner: taiga
    group: taiga
    mode: 0644

#- name: Execute install script
#  command: /bin/bash /home/taiga/taiga-back/install.sh