---
# http://taigaio.github.io/taiga-doc/dist/setup-production.html

- name: Setup python environment
  become: yes
  become_user: root
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python3
    - python3-pip
    - python-dev
    - python3-dev
    - python-pip
    - virtualenvwrapper
    - libxml2-dev
    - libxslt-dev
